_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 11
                - 12
                - 41
                - 45
                - 49
                - 51
                - 55
            "2":
                - 1
                - 11
                - 12
                - 41
                - 45
                - 49
                - 51
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
                - 61
            "4": 3.11.14
            "5": 0.19.11
            "6": 4.53.2
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
assets_base_dir:
    value: ./assets
batch_size:
    value: 16
checkpoint_base_dir:
    value: ./checkpoints
data:
    value:
        assets:
            asset_id: null
            assets_dir: null
        base_config: null
        default_prompt: Pick and place two green tennis balls into the bowl
        extra_delta_transform: true
        repack_transforms:
            inputs:
                - structure:
                    actions: action
                    images:
                        camera_top: observation.images.camera_top
                    state: observation.state
                    tactile: observation.tactile
            outputs: []
        repo_id: VTLA/Tactile2Action
ema_decay:
    value: null
exp_name:
    value: ACTION_TACTILE
freeze_filter:
    value: All(PathRegex(pattern=re.compile('.*llm.*'), sep='/'), Not(PathRegex(pattern=re.compile('.*lora.*'), sep='/')))
fsdp_devices:
    value: 1
keep_period:
    value: 5000
log_interval:
    value: 100
lr_schedule:
    value:
        decay_lr: 2.5e-06
        decay_steps: 30000
        peak_lr: 2.5e-05
        warmup_steps: 1000
model:
    value:
        action_dim: 32
        action_expert_variant: gemma_300m_lora
        action_horizon: 50
        discrete_state_input: true
        discrete_tactile_input: true
        dtype: bfloat16
        max_token_len: 512
        paligemma_variant: gemma_2b_lora
        pi05: true
        tactile_mode: ACTION_TACTILE
name:
    value: pi05_lora_tactile
num_train_steps:
    value: 20000
num_workers:
    value: 8
optimizer:
    value:
        b1: 0.9
        b2: 0.95
        clip_gradient_norm: 1
        eps: 1e-08
        weight_decay: 1e-10
overwrite:
    value: true
policy_metadata:
    value: null
project_name:
    value: openpi
pytorch_training_precision:
    value: bfloat16
pytorch_weight_path:
    value: null
resume:
    value: false
save_interval:
    value: 5000
seed:
    value: 42
wandb_enabled:
    value: true
weight_loader:
    value:
        params_path: gs://openpi-assets/checkpoints/pi05_base/params
